#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Jun 19 20:33:01 CST 2023
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto ea19f2f73fc745b996f3be612b49ff9c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot apatb_DCT_top_behav xil_defaultlib.apatb_DCT_top xil_defaultlib.glbl -log elaborate.log"
xelab -wto ea19f2f73fc745b996f3be612b49ff9c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot apatb_DCT_top_behav xil_defaultlib.apatb_DCT_top xil_defaultlib.glbl -log elaborate.log

