// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module DCT_1D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        input_0_address0,
        input_0_ce0,
        input_0_q0,
        input_1_address0,
        input_1_ce0,
        input_1_q0,
        input_2_address0,
        input_2_ce0,
        input_2_q0,
        input_3_address0,
        input_3_ce0,
        input_3_q0,
        input_4_address0,
        input_4_ce0,
        input_4_q0,
        input_5_address0,
        input_5_ce0,
        input_5_q0,
        input_6_address0,
        input_6_ce0,
        input_6_q0,
        input_7_address0,
        input_7_ce0,
        input_7_q0,
        input_offset,
        output_offset,
        DCT_1D_out_buf_col_0_address0,
        DCT_1D_out_buf_col_0_ce0,
        DCT_1D_out_buf_col_0_we0,
        DCT_1D_out_buf_col_0_d0,
        DCT_1D_out_buf_col_1_address0,
        DCT_1D_out_buf_col_1_ce0,
        DCT_1D_out_buf_col_1_we0,
        DCT_1D_out_buf_col_1_d0,
        DCT_1D_out_buf_col_2_address0,
        DCT_1D_out_buf_col_2_ce0,
        DCT_1D_out_buf_col_2_we0,
        DCT_1D_out_buf_col_2_d0,
        DCT_1D_out_buf_col_3_address0,
        DCT_1D_out_buf_col_3_ce0,
        DCT_1D_out_buf_col_3_we0,
        DCT_1D_out_buf_col_3_d0,
        DCT_1D_out_buf_col_4_address0,
        DCT_1D_out_buf_col_4_ce0,
        DCT_1D_out_buf_col_4_we0,
        DCT_1D_out_buf_col_4_d0,
        DCT_1D_out_buf_col_5_address0,
        DCT_1D_out_buf_col_5_ce0,
        DCT_1D_out_buf_col_5_we0,
        DCT_1D_out_buf_col_5_d0,
        DCT_1D_out_buf_col_6_address0,
        DCT_1D_out_buf_col_6_ce0,
        DCT_1D_out_buf_col_6_we0,
        DCT_1D_out_buf_col_6_d0,
        DCT_1D_out_buf_col_7_address0,
        DCT_1D_out_buf_col_7_ce0,
        DCT_1D_out_buf_col_7_we0,
        DCT_1D_out_buf_col_7_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
output  [2:0] input_0_address0;
output   input_0_ce0;
input  [15:0] input_0_q0;
output  [2:0] input_1_address0;
output   input_1_ce0;
input  [15:0] input_1_q0;
output  [2:0] input_2_address0;
output   input_2_ce0;
input  [15:0] input_2_q0;
output  [2:0] input_3_address0;
output   input_3_ce0;
input  [15:0] input_3_q0;
output  [2:0] input_4_address0;
output   input_4_ce0;
input  [15:0] input_4_q0;
output  [2:0] input_5_address0;
output   input_5_ce0;
input  [15:0] input_5_q0;
output  [2:0] input_6_address0;
output   input_6_ce0;
input  [15:0] input_6_q0;
output  [2:0] input_7_address0;
output   input_7_ce0;
input  [15:0] input_7_q0;
input  [3:0] input_offset;
input  [3:0] output_offset;
output  [2:0] DCT_1D_out_buf_col_0_address0;
output   DCT_1D_out_buf_col_0_ce0;
output   DCT_1D_out_buf_col_0_we0;
output  [15:0] DCT_1D_out_buf_col_0_d0;
output  [2:0] DCT_1D_out_buf_col_1_address0;
output   DCT_1D_out_buf_col_1_ce0;
output   DCT_1D_out_buf_col_1_we0;
output  [15:0] DCT_1D_out_buf_col_1_d0;
output  [2:0] DCT_1D_out_buf_col_2_address0;
output   DCT_1D_out_buf_col_2_ce0;
output   DCT_1D_out_buf_col_2_we0;
output  [15:0] DCT_1D_out_buf_col_2_d0;
output  [2:0] DCT_1D_out_buf_col_3_address0;
output   DCT_1D_out_buf_col_3_ce0;
output   DCT_1D_out_buf_col_3_we0;
output  [15:0] DCT_1D_out_buf_col_3_d0;
output  [2:0] DCT_1D_out_buf_col_4_address0;
output   DCT_1D_out_buf_col_4_ce0;
output   DCT_1D_out_buf_col_4_we0;
output  [15:0] DCT_1D_out_buf_col_4_d0;
output  [2:0] DCT_1D_out_buf_col_5_address0;
output   DCT_1D_out_buf_col_5_ce0;
output   DCT_1D_out_buf_col_5_we0;
output  [15:0] DCT_1D_out_buf_col_5_d0;
output  [2:0] DCT_1D_out_buf_col_6_address0;
output   DCT_1D_out_buf_col_6_ce0;
output   DCT_1D_out_buf_col_6_we0;
output  [15:0] DCT_1D_out_buf_col_6_d0;
output  [2:0] DCT_1D_out_buf_col_7_address0;
output   DCT_1D_out_buf_col_7_ce0;
output   DCT_1D_out_buf_col_7_we0;
output  [15:0] DCT_1D_out_buf_col_7_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_0_ce0;
reg input_1_ce0;
reg input_2_ce0;
reg input_3_ce0;
reg input_4_ce0;
reg input_5_ce0;
reg input_6_ce0;
reg input_7_ce0;
reg DCT_1D_out_buf_col_0_ce0;
reg DCT_1D_out_buf_col_0_we0;
reg DCT_1D_out_buf_col_1_ce0;
reg DCT_1D_out_buf_col_1_we0;
reg DCT_1D_out_buf_col_2_ce0;
reg DCT_1D_out_buf_col_2_we0;
reg DCT_1D_out_buf_col_3_ce0;
reg DCT_1D_out_buf_col_3_we0;
reg DCT_1D_out_buf_col_4_ce0;
reg DCT_1D_out_buf_col_4_we0;
reg DCT_1D_out_buf_col_5_ce0;
reg DCT_1D_out_buf_col_5_we0;
reg DCT_1D_out_buf_col_6_ce0;
reg DCT_1D_out_buf_col_6_we0;
reg DCT_1D_out_buf_col_7_ce0;
reg DCT_1D_out_buf_col_7_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [3:0] output_offset_read_reg_1203;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] input_offset_cast_fu_318_p1;
wire   [63:0] output_offset_cast_fu_330_p1;
wire  signed [15:0] sext_ln50_54_fu_349_p0;
wire  signed [15:0] sext_ln50_55_fu_353_p0;
wire  signed [15:0] sext_ln50_57_fu_361_p0;
wire  signed [15:0] sext_ln50_58_fu_365_p0;
wire  signed [15:0] sext_ln50_59_fu_369_p0;
wire  signed [15:0] sext_ln50_61_fu_377_p0;
wire  signed [15:0] sext_ln50_62_fu_381_p0;
wire  signed [15:0] sext_ln50_63_fu_385_p0;
wire  signed [15:0] sext_ln50_65_fu_393_p0;
wire  signed [15:0] sext_ln50_67_fu_401_p0;
wire  signed [15:0] sext_ln50_69_fu_409_p0;
wire  signed [15:0] sext_ln50_71_fu_417_p0;
wire  signed [15:0] sext_ln50_73_fu_425_p0;
wire  signed [15:0] sext_ln50_74_fu_429_p0;
wire  signed [15:0] sext_ln50_75_fu_433_p0;
wire  signed [15:0] sext_ln50_77_fu_441_p0;
wire  signed [15:0] sext_ln50_78_fu_445_p0;
wire  signed [15:0] sext_ln50_79_fu_449_p0;
wire  signed [15:0] sext_ln50_82_fu_461_p0;
wire  signed [16:0] sext_ln50_59_fu_369_p1;
wire  signed [16:0] sext_ln50_55_fu_353_p1;
wire   [16:0] add_ln50_fu_465_p2;
wire  signed [16:0] sext_ln50_67_fu_401_p1;
wire  signed [16:0] sext_ln50_63_fu_385_p1;
wire   [16:0] add_ln50_7_fu_475_p2;
wire  signed [17:0] sext_ln50_83_fu_471_p1;
wire  signed [17:0] sext_ln50_84_fu_481_p1;
wire  signed [17:0] add_ln50_8_fu_485_p2;
wire  signed [16:0] sext_ln50_75_fu_433_p1;
wire  signed [16:0] sext_ln50_71_fu_417_p1;
wire   [16:0] add_ln50_9_fu_495_p2;
wire  signed [16:0] sext_ln50_82_fu_461_p1;
wire  signed [16:0] sext_ln50_79_fu_449_p1;
wire   [16:0] add_ln50_10_fu_505_p2;
wire  signed [17:0] sext_ln50_86_fu_501_p1;
wire  signed [17:0] sext_ln50_87_fu_511_p1;
wire  signed [17:0] add_ln50_11_fu_515_p2;
wire  signed [28:0] grp_fu_751_p4;
wire  signed [15:0] sext_ln50_92_fu_535_p0;
wire  signed [27:0] grp_fu_783_p3;
wire  signed [28:0] grp_fu_762_p3;
wire  signed [28:0] sext_ln52_fu_539_p1;
wire  signed [27:0] grp_fu_792_p3;
wire  signed [27:0] grp_fu_816_p3;
wire  signed [28:0] sext_ln52_11_fu_547_p1;
wire  signed [28:0] grp_fu_807_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln52_59_fu_542_p2;
(* use_dsp48 = "no" *) wire   [28:0] add_ln52_63_fu_553_p2;
wire   [28:0] add_ln52_1_fu_558_p2;
wire  signed [28:0] grp_fu_831_p3;
wire  signed [28:0] grp_fu_840_p3;
wire  signed [27:0] grp_fu_879_p3;
wire  signed [28:0] grp_fu_861_p3;
wire  signed [28:0] grp_fu_870_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln52_66_fu_575_p2;
(* use_dsp48 = "no" *) wire   [28:0] add_ln52_70_fu_582_p2;
wire   [28:0] add_ln52_2_fu_586_p2;
wire  signed [28:0] grp_fu_894_p3;
wire  signed [28:0] grp_fu_903_p3;
wire  signed [27:0] grp_fu_942_p3;
wire  signed [28:0] grp_fu_918_p3;
wire  signed [28:0] grp_fu_933_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln52_73_fu_603_p2;
(* use_dsp48 = "no" *) wire   [28:0] add_ln52_77_fu_610_p2;
wire   [28:0] add_ln52_3_fu_614_p2;
wire  signed [28:0] grp_fu_951_p3;
wire  signed [28:0] grp_fu_966_p3;
wire  signed [27:0] grp_fu_1005_p3;
wire  signed [28:0] grp_fu_981_p3;
wire  signed [28:0] grp_fu_996_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln52_80_fu_631_p2;
(* use_dsp48 = "no" *) wire   [28:0] add_ln52_84_fu_638_p2;
wire   [28:0] add_ln52_4_fu_642_p2;
wire  signed [28:0] grp_fu_1014_p3;
wire  signed [28:0] grp_fu_1029_p3;
wire  signed [27:0] grp_fu_1068_p3;
wire  signed [28:0] grp_fu_1050_p3;
wire  signed [28:0] grp_fu_1059_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln52_87_fu_659_p2;
(* use_dsp48 = "no" *) wire   [28:0] add_ln52_91_fu_666_p2;
wire   [28:0] add_ln52_5_fu_670_p2;
wire  signed [28:0] grp_fu_1077_p3;
wire  signed [28:0] grp_fu_1098_p3;
wire  signed [26:0] grp_fu_1131_p3;
wire  signed [28:0] grp_fu_1107_p3;
wire  signed [28:0] grp_fu_1122_p3;
(* use_dsp48 = "no" *) wire   [28:0] add_ln52_94_fu_687_p2;
(* use_dsp48 = "no" *) wire   [28:0] add_ln52_98_fu_694_p2;
wire   [28:0] add_ln52_6_fu_698_p2;
wire  signed [27:0] grp_fu_1140_p3;
wire  signed [28:0] sext_ln52_18_fu_715_p1;
wire  signed [28:0] grp_fu_1155_p3;
wire  signed [25:0] grp_fu_1194_p3;
wire  signed [27:0] grp_fu_1185_p3;
wire  signed [28:0] grp_fu_1170_p3;
wire  signed [28:0] sext_ln52_20_fu_726_p1;
(* use_dsp48 = "no" *) wire   [28:0] add_ln52_101_fu_718_p2;
(* use_dsp48 = "no" *) wire   [28:0] add_ln52_105_fu_729_p2;
wire   [28:0] add_ln52_7_fu_734_p2;
wire   [12:0] grp_fu_751_p2;
wire   [13:0] grp_fu_751_p3;
wire  signed [15:0] grp_fu_762_p0;
wire  signed [28:0] sext_ln50_54_fu_349_p1;
wire   [12:0] grp_fu_762_p1;
wire  signed [28:0] mul_ln50_58_fu_770_p2;
wire  signed [15:0] mul_ln50_58_fu_770_p0;
wire  signed [28:0] sext_ln50_58_fu_365_p1;
wire   [12:0] mul_ln50_58_fu_770_p1;
wire  signed [15:0] mul_ln50_59_fu_777_p0;
wire  signed [27:0] sext_ln50_61_fu_377_p1;
wire   [12:0] mul_ln50_59_fu_777_p1;
wire   [10:0] grp_fu_783_p1;
wire  signed [27:0] mul_ln50_59_fu_777_p2;
wire  signed [10:0] grp_fu_792_p1;
wire  signed [27:0] mul_ln50_62_fu_800_p2;
wire  signed [15:0] mul_ln50_62_fu_800_p0;
wire  signed [27:0] sext_ln50_73_fu_425_p1;
wire  signed [12:0] mul_ln50_62_fu_800_p1;
wire  signed [15:0] grp_fu_807_p0;
wire  signed [28:0] sext_ln50_78_fu_445_p1;
wire  signed [12:0] grp_fu_807_p1;
wire  signed [15:0] grp_fu_816_p0;
wire  signed [27:0] sext_ln50_92_fu_535_p1;
wire  signed [12:0] grp_fu_816_p1;
wire   [13:0] grp_fu_816_p2;
wire  signed [15:0] mul_ln50_65_fu_825_p0;
wire   [12:0] mul_ln50_65_fu_825_p1;
wire  signed [15:0] grp_fu_831_p0;
wire  signed [27:0] sext_ln50_57_fu_361_p1;
wire   [11:0] grp_fu_831_p1;
wire  signed [28:0] mul_ln50_65_fu_825_p2;
wire  signed [15:0] grp_fu_840_p0;
wire  signed [11:0] grp_fu_840_p1;
wire  signed [28:0] mul_ln50_68_fu_848_p2;
wire  signed [15:0] mul_ln50_68_fu_848_p0;
wire  signed [28:0] sext_ln50_65_fu_393_p1;
wire  signed [12:0] mul_ln50_68_fu_848_p1;
wire  signed [15:0] mul_ln50_69_fu_855_p0;
wire  signed [28:0] sext_ln50_69_fu_409_p1;
wire  signed [12:0] mul_ln50_69_fu_855_p1;
wire  signed [15:0] grp_fu_861_p0;
wire  signed [11:0] grp_fu_861_p1;
wire  signed [28:0] mul_ln50_69_fu_855_p2;
wire  signed [15:0] grp_fu_870_p0;
wire  signed [27:0] sext_ln50_77_fu_441_p1;
wire   [11:0] grp_fu_870_p1;
wire  signed [15:0] grp_fu_879_p0;
wire   [12:0] grp_fu_879_p1;
wire   [13:0] grp_fu_879_p2;
wire  signed [15:0] mul_ln50_73_fu_888_p0;
wire   [12:0] mul_ln50_73_fu_888_p1;
wire  signed [10:0] grp_fu_894_p1;
wire  signed [28:0] mul_ln50_73_fu_888_p2;
wire  signed [15:0] grp_fu_903_p0;
wire  signed [28:0] sext_ln50_62_fu_381_p1;
wire  signed [12:0] grp_fu_903_p1;
wire  signed [28:0] mul_ln50_76_fu_911_p2;
wire  signed [15:0] mul_ln50_76_fu_911_p0;
wire  signed [12:0] mul_ln50_76_fu_911_p1;
wire  signed [15:0] grp_fu_918_p0;
wire   [12:0] grp_fu_918_p1;
wire  signed [28:0] mul_ln50_78_fu_926_p2;
wire  signed [15:0] mul_ln50_78_fu_926_p0;
wire  signed [28:0] sext_ln50_74_fu_429_p1;
wire   [12:0] mul_ln50_78_fu_926_p1;
wire   [10:0] grp_fu_933_p1;
wire  signed [15:0] grp_fu_942_p0;
wire  signed [12:0] grp_fu_942_p1;
wire   [13:0] grp_fu_942_p2;
wire  signed [15:0] grp_fu_951_p0;
wire   [12:0] grp_fu_951_p1;
wire  signed [28:0] mul_ln50_82_fu_959_p2;
wire  signed [15:0] mul_ln50_82_fu_959_p0;
wire  signed [12:0] mul_ln50_82_fu_959_p1;
wire  signed [15:0] grp_fu_966_p0;
wire  signed [12:0] grp_fu_966_p1;
wire  signed [28:0] mul_ln50_84_fu_974_p2;
wire  signed [15:0] mul_ln50_84_fu_974_p0;
wire   [12:0] mul_ln50_84_fu_974_p1;
wire  signed [15:0] grp_fu_981_p0;
wire   [12:0] grp_fu_981_p1;
wire  signed [28:0] mul_ln50_86_fu_989_p2;
wire  signed [15:0] mul_ln50_86_fu_989_p0;
wire  signed [12:0] mul_ln50_86_fu_989_p1;
wire  signed [15:0] grp_fu_996_p0;
wire  signed [12:0] grp_fu_996_p1;
wire  signed [15:0] grp_fu_1005_p0;
wire   [12:0] grp_fu_1005_p1;
wire   [13:0] grp_fu_1005_p2;
wire  signed [15:0] grp_fu_1014_p0;
wire   [12:0] grp_fu_1014_p1;
wire  signed [28:0] mul_ln50_90_fu_1022_p2;
wire  signed [15:0] mul_ln50_90_fu_1022_p0;
wire  signed [12:0] mul_ln50_90_fu_1022_p1;
wire   [10:0] grp_fu_1029_p1;
wire  signed [28:0] mul_ln50_92_fu_1037_p2;
wire  signed [15:0] mul_ln50_92_fu_1037_p0;
wire   [12:0] mul_ln50_92_fu_1037_p1;
wire  signed [15:0] mul_ln50_93_fu_1044_p0;
wire  signed [12:0] mul_ln50_93_fu_1044_p1;
wire  signed [10:0] grp_fu_1050_p1;
wire  signed [28:0] mul_ln50_93_fu_1044_p2;
wire  signed [15:0] grp_fu_1059_p0;
wire   [12:0] grp_fu_1059_p1;
wire  signed [15:0] grp_fu_1068_p0;
wire  signed [12:0] grp_fu_1068_p1;
wire   [13:0] grp_fu_1068_p2;
wire   [11:0] grp_fu_1077_p1;
wire  signed [28:0] mul_ln50_98_fu_1085_p2;
wire  signed [15:0] mul_ln50_98_fu_1085_p0;
wire  signed [12:0] mul_ln50_98_fu_1085_p1;
wire  signed [15:0] mul_ln50_99_fu_1092_p0;
wire   [12:0] mul_ln50_99_fu_1092_p1;
wire  signed [11:0] grp_fu_1098_p1;
wire  signed [28:0] mul_ln50_99_fu_1092_p2;
wire  signed [11:0] grp_fu_1107_p1;
wire  signed [28:0] mul_ln50_102_fu_1115_p2;
wire  signed [15:0] mul_ln50_102_fu_1115_p0;
wire   [12:0] mul_ln50_102_fu_1115_p1;
wire  signed [15:0] grp_fu_1122_p0;
wire  signed [12:0] grp_fu_1122_p1;
wire   [11:0] grp_fu_1131_p1;
wire   [13:0] grp_fu_1131_p2;
wire   [10:0] grp_fu_1140_p1;
wire  signed [27:0] mul_ln50_106_fu_1148_p2;
wire  signed [15:0] mul_ln50_106_fu_1148_p0;
wire  signed [12:0] mul_ln50_106_fu_1148_p1;
wire  signed [15:0] grp_fu_1155_p0;
wire   [12:0] grp_fu_1155_p1;
wire  signed [28:0] mul_ln50_108_fu_1163_p2;
wire  signed [15:0] mul_ln50_108_fu_1163_p0;
wire  signed [12:0] mul_ln50_108_fu_1163_p1;
wire  signed [15:0] grp_fu_1170_p0;
wire   [12:0] grp_fu_1170_p1;
wire  signed [28:0] mul_ln50_110_fu_1178_p2;
wire  signed [15:0] mul_ln50_110_fu_1178_p0;
wire  signed [12:0] mul_ln50_110_fu_1178_p1;
wire  signed [15:0] grp_fu_1185_p0;
wire   [12:0] grp_fu_1185_p1;
wire  signed [10:0] grp_fu_1194_p1;
wire   [13:0] grp_fu_1194_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_reset_start_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

DCT_ama_addmuladdbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 18 ),
    .din2_WIDTH( 13 ),
    .din3_WIDTH( 14 ),
    .dout_WIDTH( 29 ))
DCT_ama_addmuladdbkb_U131(
    .din0(add_ln50_8_fu_485_p2),
    .din1(add_ln50_11_fu_515_p2),
    .din2(grp_fu_751_p2),
    .din3(grp_fu_751_p3),
    .dout(grp_fu_751_p4)
);

DCT_mac_muladd_16cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16cud_U132(
    .din0(grp_fu_762_p0),
    .din1(grp_fu_762_p1),
    .din2(mul_ln50_58_fu_770_p2),
    .dout(grp_fu_762_p3)
);

DCT_mul_mul_16s_1dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
DCT_mul_mul_16s_1dEe_U133(
    .din0(mul_ln50_58_fu_770_p0),
    .din1(mul_ln50_58_fu_770_p1),
    .dout(mul_ln50_58_fu_770_p2)
);

DCT_mul_mul_16s_1eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 28 ))
DCT_mul_mul_16s_1eOg_U134(
    .din0(mul_ln50_59_fu_777_p0),
    .din1(mul_ln50_59_fu_777_p1),
    .dout(mul_ln50_59_fu_777_p2)
);

DCT_mac_muladd_16fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
DCT_mac_muladd_16fYi_U135(
    .din0(input_3_q0),
    .din1(grp_fu_783_p1),
    .din2(mul_ln50_59_fu_777_p2),
    .dout(grp_fu_783_p3)
);

DCT_mac_muladd_16g8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
DCT_mac_muladd_16g8j_U136(
    .din0(input_4_q0),
    .din1(grp_fu_792_p1),
    .din2(mul_ln50_62_fu_800_p2),
    .dout(grp_fu_792_p3)
);

DCT_mul_mul_16s_1hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 28 ))
DCT_mul_mul_16s_1hbi_U137(
    .din0(mul_ln50_62_fu_800_p0),
    .din1(mul_ln50_62_fu_800_p1),
    .dout(mul_ln50_62_fu_800_p2)
);

DCT_mac_muladd_16ibs #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16ibs_U138(
    .din0(grp_fu_807_p0),
    .din1(grp_fu_807_p1),
    .din2(grp_fu_816_p3),
    .dout(grp_fu_807_p3)
);

DCT_mac_muladd_16jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 28 ))
DCT_mac_muladd_16jbC_U139(
    .din0(grp_fu_816_p0),
    .din1(grp_fu_816_p1),
    .din2(grp_fu_816_p2),
    .dout(grp_fu_816_p3)
);

DCT_mul_mul_16s_1dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
DCT_mul_mul_16s_1dEe_U140(
    .din0(mul_ln50_65_fu_825_p0),
    .din1(mul_ln50_65_fu_825_p1),
    .dout(mul_ln50_65_fu_825_p2)
);

DCT_mac_muladd_16kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16kbM_U141(
    .din0(grp_fu_831_p0),
    .din1(grp_fu_831_p1),
    .din2(mul_ln50_65_fu_825_p2),
    .dout(grp_fu_831_p3)
);

DCT_mac_muladd_16lbW #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16lbW_U142(
    .din0(grp_fu_840_p0),
    .din1(grp_fu_840_p1),
    .din2(mul_ln50_68_fu_848_p2),
    .dout(grp_fu_840_p3)
);

DCT_mul_mul_16s_1mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
DCT_mul_mul_16s_1mb6_U143(
    .din0(mul_ln50_68_fu_848_p0),
    .din1(mul_ln50_68_fu_848_p1),
    .dout(mul_ln50_68_fu_848_p2)
);

DCT_mul_mul_16s_1mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
DCT_mul_mul_16s_1mb6_U144(
    .din0(mul_ln50_69_fu_855_p0),
    .din1(mul_ln50_69_fu_855_p1),
    .dout(mul_ln50_69_fu_855_p2)
);

DCT_mac_muladd_16lbW #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16lbW_U145(
    .din0(grp_fu_861_p0),
    .din1(grp_fu_861_p1),
    .din2(mul_ln50_69_fu_855_p2),
    .dout(grp_fu_861_p3)
);

DCT_mac_muladd_16ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16ncg_U146(
    .din0(grp_fu_870_p0),
    .din1(grp_fu_870_p1),
    .din2(grp_fu_879_p3),
    .dout(grp_fu_870_p3)
);

DCT_mac_muladd_16ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 28 ))
DCT_mac_muladd_16ocq_U147(
    .din0(grp_fu_879_p0),
    .din1(grp_fu_879_p1),
    .din2(grp_fu_879_p2),
    .dout(grp_fu_879_p3)
);

DCT_mul_mul_16s_1dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
DCT_mul_mul_16s_1dEe_U148(
    .din0(mul_ln50_73_fu_888_p0),
    .din1(mul_ln50_73_fu_888_p1),
    .dout(mul_ln50_73_fu_888_p2)
);

DCT_mac_muladd_16pcA #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16pcA_U149(
    .din0(input_1_q0),
    .din1(grp_fu_894_p1),
    .din2(mul_ln50_73_fu_888_p2),
    .dout(grp_fu_894_p3)
);

DCT_mac_muladd_16qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16qcK_U150(
    .din0(grp_fu_903_p0),
    .din1(grp_fu_903_p1),
    .din2(mul_ln50_76_fu_911_p2),
    .dout(grp_fu_903_p3)
);

DCT_mul_mul_16s_1mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
DCT_mul_mul_16s_1mb6_U151(
    .din0(mul_ln50_76_fu_911_p0),
    .din1(mul_ln50_76_fu_911_p1),
    .dout(mul_ln50_76_fu_911_p2)
);

DCT_mac_muladd_16cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16cud_U152(
    .din0(grp_fu_918_p0),
    .din1(grp_fu_918_p1),
    .din2(mul_ln50_78_fu_926_p2),
    .dout(grp_fu_918_p3)
);

DCT_mul_mul_16s_1dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
DCT_mul_mul_16s_1dEe_U153(
    .din0(mul_ln50_78_fu_926_p0),
    .din1(mul_ln50_78_fu_926_p1),
    .dout(mul_ln50_78_fu_926_p2)
);

DCT_mac_muladd_16rcU #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16rcU_U154(
    .din0(input_6_q0),
    .din1(grp_fu_933_p1),
    .din2(grp_fu_942_p3),
    .dout(grp_fu_933_p3)
);

DCT_mac_muladd_16jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 28 ))
DCT_mac_muladd_16jbC_U155(
    .din0(grp_fu_942_p0),
    .din1(grp_fu_942_p1),
    .din2(grp_fu_942_p2),
    .dout(grp_fu_942_p3)
);

DCT_mac_muladd_16cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16cud_U156(
    .din0(grp_fu_951_p0),
    .din1(grp_fu_951_p1),
    .din2(mul_ln50_82_fu_959_p2),
    .dout(grp_fu_951_p3)
);

DCT_mul_mul_16s_1mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
DCT_mul_mul_16s_1mb6_U157(
    .din0(mul_ln50_82_fu_959_p0),
    .din1(mul_ln50_82_fu_959_p1),
    .dout(mul_ln50_82_fu_959_p2)
);

DCT_mac_muladd_16qcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16qcK_U158(
    .din0(grp_fu_966_p0),
    .din1(grp_fu_966_p1),
    .din2(mul_ln50_84_fu_974_p2),
    .dout(grp_fu_966_p3)
);

DCT_mul_mul_16s_1dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
DCT_mul_mul_16s_1dEe_U159(
    .din0(mul_ln50_84_fu_974_p0),
    .din1(mul_ln50_84_fu_974_p1),
    .dout(mul_ln50_84_fu_974_p2)
);

DCT_mac_muladd_16cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16cud_U160(
    .din0(grp_fu_981_p0),
    .din1(grp_fu_981_p1),
    .din2(mul_ln50_86_fu_989_p2),
    .dout(grp_fu_981_p3)
);

DCT_mul_mul_16s_1mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
DCT_mul_mul_16s_1mb6_U161(
    .din0(mul_ln50_86_fu_989_p0),
    .din1(mul_ln50_86_fu_989_p1),
    .dout(mul_ln50_86_fu_989_p2)
);

DCT_mac_muladd_16ibs #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16ibs_U162(
    .din0(grp_fu_996_p0),
    .din1(grp_fu_996_p1),
    .din2(grp_fu_1005_p3),
    .dout(grp_fu_996_p3)
);

DCT_mac_muladd_16ocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 28 ))
DCT_mac_muladd_16ocq_U163(
    .din0(grp_fu_1005_p0),
    .din1(grp_fu_1005_p1),
    .din2(grp_fu_1005_p2),
    .dout(grp_fu_1005_p3)
);

DCT_mac_muladd_16cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16cud_U164(
    .din0(grp_fu_1014_p0),
    .din1(grp_fu_1014_p1),
    .din2(mul_ln50_90_fu_1022_p2),
    .dout(grp_fu_1014_p3)
);

DCT_mul_mul_16s_1mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
DCT_mul_mul_16s_1mb6_U165(
    .din0(mul_ln50_90_fu_1022_p0),
    .din1(mul_ln50_90_fu_1022_p1),
    .dout(mul_ln50_90_fu_1022_p2)
);

DCT_mac_muladd_16sc4 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16sc4_U166(
    .din0(input_2_q0),
    .din1(grp_fu_1029_p1),
    .din2(mul_ln50_92_fu_1037_p2),
    .dout(grp_fu_1029_p3)
);

DCT_mul_mul_16s_1dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
DCT_mul_mul_16s_1dEe_U167(
    .din0(mul_ln50_92_fu_1037_p0),
    .din1(mul_ln50_92_fu_1037_p1),
    .dout(mul_ln50_92_fu_1037_p2)
);

DCT_mul_mul_16s_1mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
DCT_mul_mul_16s_1mb6_U168(
    .din0(mul_ln50_93_fu_1044_p0),
    .din1(mul_ln50_93_fu_1044_p1),
    .dout(mul_ln50_93_fu_1044_p2)
);

DCT_mac_muladd_16pcA #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16pcA_U169(
    .din0(input_5_q0),
    .din1(grp_fu_1050_p1),
    .din2(mul_ln50_93_fu_1044_p2),
    .dout(grp_fu_1050_p3)
);

DCT_mac_muladd_16tde #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16tde_U170(
    .din0(grp_fu_1059_p0),
    .din1(grp_fu_1059_p1),
    .din2(grp_fu_1068_p3),
    .dout(grp_fu_1059_p3)
);

DCT_mac_muladd_16jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 28 ))
DCT_mac_muladd_16jbC_U171(
    .din0(grp_fu_1068_p0),
    .din1(grp_fu_1068_p1),
    .din2(grp_fu_1068_p2),
    .dout(grp_fu_1068_p3)
);

DCT_mac_muladd_16kbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16kbM_U172(
    .din0(input_0_q0),
    .din1(grp_fu_1077_p1),
    .din2(mul_ln50_98_fu_1085_p2),
    .dout(grp_fu_1077_p3)
);

DCT_mul_mul_16s_1mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
DCT_mul_mul_16s_1mb6_U173(
    .din0(mul_ln50_98_fu_1085_p0),
    .din1(mul_ln50_98_fu_1085_p1),
    .dout(mul_ln50_98_fu_1085_p2)
);

DCT_mul_mul_16s_1dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
DCT_mul_mul_16s_1dEe_U174(
    .din0(mul_ln50_99_fu_1092_p0),
    .din1(mul_ln50_99_fu_1092_p1),
    .dout(mul_ln50_99_fu_1092_p2)
);

DCT_mac_muladd_16lbW #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16lbW_U175(
    .din0(input_3_q0),
    .din1(grp_fu_1098_p1),
    .din2(mul_ln50_99_fu_1092_p2),
    .dout(grp_fu_1098_p3)
);

DCT_mac_muladd_16lbW #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16lbW_U176(
    .din0(input_4_q0),
    .din1(grp_fu_1107_p1),
    .din2(mul_ln50_102_fu_1115_p2),
    .dout(grp_fu_1107_p3)
);

DCT_mul_mul_16s_1dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
DCT_mul_mul_16s_1dEe_U177(
    .din0(mul_ln50_102_fu_1115_p0),
    .din1(mul_ln50_102_fu_1115_p1),
    .dout(mul_ln50_102_fu_1115_p2)
);

DCT_mac_muladd_16udo #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 27 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16udo_U178(
    .din0(grp_fu_1122_p0),
    .din1(grp_fu_1122_p1),
    .din2(grp_fu_1131_p3),
    .dout(grp_fu_1122_p3)
);

DCT_mac_muladd_16vdy #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 27 ))
DCT_mac_muladd_16vdy_U179(
    .din0(input_7_q0),
    .din1(grp_fu_1131_p1),
    .din2(grp_fu_1131_p2),
    .dout(grp_fu_1131_p3)
);

DCT_mac_muladd_16fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
DCT_mac_muladd_16fYi_U180(
    .din0(input_0_q0),
    .din1(grp_fu_1140_p1),
    .din2(mul_ln50_106_fu_1148_p2),
    .dout(grp_fu_1140_p3)
);

DCT_mul_mul_16s_1hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 28 ))
DCT_mul_mul_16s_1hbi_U181(
    .din0(mul_ln50_106_fu_1148_p0),
    .din1(mul_ln50_106_fu_1148_p1),
    .dout(mul_ln50_106_fu_1148_p2)
);

DCT_mac_muladd_16cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16cud_U182(
    .din0(grp_fu_1155_p0),
    .din1(grp_fu_1155_p1),
    .din2(mul_ln50_108_fu_1163_p2),
    .dout(grp_fu_1155_p3)
);

DCT_mul_mul_16s_1mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
DCT_mul_mul_16s_1mb6_U183(
    .din0(mul_ln50_108_fu_1163_p0),
    .din1(mul_ln50_108_fu_1163_p1),
    .dout(mul_ln50_108_fu_1163_p2)
);

DCT_mac_muladd_16cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
DCT_mac_muladd_16cud_U184(
    .din0(grp_fu_1170_p0),
    .din1(grp_fu_1170_p1),
    .din2(mul_ln50_110_fu_1178_p2),
    .dout(grp_fu_1170_p3)
);

DCT_mul_mul_16s_1mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
DCT_mul_mul_16s_1mb6_U185(
    .din0(mul_ln50_110_fu_1178_p0),
    .din1(mul_ln50_110_fu_1178_p1),
    .dout(mul_ln50_110_fu_1178_p2)
);

DCT_mac_muladd_16wdI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 28 ))
DCT_mac_muladd_16wdI_U186(
    .din0(grp_fu_1185_p0),
    .din1(grp_fu_1185_p1),
    .din2(grp_fu_1194_p3),
    .dout(grp_fu_1185_p3)
);

DCT_mac_muladd_16xdS #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 26 ))
DCT_mac_muladd_16xdS_U187(
    .din0(input_7_q0),
    .din1(grp_fu_1194_p1),
    .din2(grp_fu_1194_p2),
    .dout(grp_fu_1194_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_offset_read_reg_1203 <= output_offset;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCT_1D_out_buf_col_0_ce0 = 1'b1;
    end else begin
        DCT_1D_out_buf_col_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCT_1D_out_buf_col_0_we0 = 1'b1;
    end else begin
        DCT_1D_out_buf_col_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCT_1D_out_buf_col_1_ce0 = 1'b1;
    end else begin
        DCT_1D_out_buf_col_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCT_1D_out_buf_col_1_we0 = 1'b1;
    end else begin
        DCT_1D_out_buf_col_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCT_1D_out_buf_col_2_ce0 = 1'b1;
    end else begin
        DCT_1D_out_buf_col_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCT_1D_out_buf_col_2_we0 = 1'b1;
    end else begin
        DCT_1D_out_buf_col_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCT_1D_out_buf_col_3_ce0 = 1'b1;
    end else begin
        DCT_1D_out_buf_col_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCT_1D_out_buf_col_3_we0 = 1'b1;
    end else begin
        DCT_1D_out_buf_col_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCT_1D_out_buf_col_4_ce0 = 1'b1;
    end else begin
        DCT_1D_out_buf_col_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCT_1D_out_buf_col_4_we0 = 1'b1;
    end else begin
        DCT_1D_out_buf_col_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCT_1D_out_buf_col_5_ce0 = 1'b1;
    end else begin
        DCT_1D_out_buf_col_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCT_1D_out_buf_col_5_we0 = 1'b1;
    end else begin
        DCT_1D_out_buf_col_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCT_1D_out_buf_col_6_ce0 = 1'b1;
    end else begin
        DCT_1D_out_buf_col_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCT_1D_out_buf_col_6_we0 = 1'b1;
    end else begin
        DCT_1D_out_buf_col_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCT_1D_out_buf_col_7_ce0 = 1'b1;
    end else begin
        DCT_1D_out_buf_col_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DCT_1D_out_buf_col_7_we0 = 1'b1;
    end else begin
        DCT_1D_out_buf_col_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (ap_start == 1'b1))) begin
        ap_reset_start_pp0 = 1'b1;
    end else begin
        ap_reset_start_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_0_ce0 = 1'b1;
    end else begin
        input_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_1_ce0 = 1'b1;
    end else begin
        input_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_2_ce0 = 1'b1;
    end else begin
        input_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_3_ce0 = 1'b1;
    end else begin
        input_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_4_ce0 = 1'b1;
    end else begin
        input_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_5_ce0 = 1'b1;
    end else begin
        input_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_6_ce0 = 1'b1;
    end else begin
        input_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_7_ce0 = 1'b1;
    end else begin
        input_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DCT_1D_out_buf_col_0_address0 = output_offset_cast_fu_330_p1;

assign DCT_1D_out_buf_col_0_d0 = {{grp_fu_751_p4[28:13]}};

assign DCT_1D_out_buf_col_1_address0 = output_offset_cast_fu_330_p1;

assign DCT_1D_out_buf_col_1_d0 = {{add_ln52_1_fu_558_p2[28:13]}};

assign DCT_1D_out_buf_col_2_address0 = output_offset_cast_fu_330_p1;

assign DCT_1D_out_buf_col_2_d0 = {{add_ln52_2_fu_586_p2[28:13]}};

assign DCT_1D_out_buf_col_3_address0 = output_offset_cast_fu_330_p1;

assign DCT_1D_out_buf_col_3_d0 = {{add_ln52_3_fu_614_p2[28:13]}};

assign DCT_1D_out_buf_col_4_address0 = output_offset_cast_fu_330_p1;

assign DCT_1D_out_buf_col_4_d0 = {{add_ln52_4_fu_642_p2[28:13]}};

assign DCT_1D_out_buf_col_5_address0 = output_offset_cast_fu_330_p1;

assign DCT_1D_out_buf_col_5_d0 = {{add_ln52_5_fu_670_p2[28:13]}};

assign DCT_1D_out_buf_col_6_address0 = output_offset_cast_fu_330_p1;

assign DCT_1D_out_buf_col_6_d0 = {{add_ln52_6_fu_698_p2[28:13]}};

assign DCT_1D_out_buf_col_7_address0 = output_offset_cast_fu_330_p1;

assign DCT_1D_out_buf_col_7_d0 = {{add_ln52_7_fu_734_p2[28:13]}};

assign add_ln50_10_fu_505_p2 = ($signed(sext_ln50_82_fu_461_p1) + $signed(sext_ln50_79_fu_449_p1));

assign add_ln50_11_fu_515_p2 = ($signed(sext_ln50_86_fu_501_p1) + $signed(sext_ln50_87_fu_511_p1));

assign add_ln50_7_fu_475_p2 = ($signed(sext_ln50_67_fu_401_p1) + $signed(sext_ln50_63_fu_385_p1));

assign add_ln50_8_fu_485_p2 = ($signed(sext_ln50_83_fu_471_p1) + $signed(sext_ln50_84_fu_481_p1));

assign add_ln50_9_fu_495_p2 = ($signed(sext_ln50_75_fu_433_p1) + $signed(sext_ln50_71_fu_417_p1));

assign add_ln50_fu_465_p2 = ($signed(sext_ln50_59_fu_369_p1) + $signed(sext_ln50_55_fu_353_p1));

assign add_ln52_101_fu_718_p2 = ($signed(sext_ln52_18_fu_715_p1) + $signed(grp_fu_1155_p3));

assign add_ln52_105_fu_729_p2 = ($signed(grp_fu_1170_p3) + $signed(sext_ln52_20_fu_726_p1));

assign add_ln52_1_fu_558_p2 = (add_ln52_59_fu_542_p2 + add_ln52_63_fu_553_p2);

assign add_ln52_2_fu_586_p2 = (add_ln52_66_fu_575_p2 + add_ln52_70_fu_582_p2);

assign add_ln52_3_fu_614_p2 = (add_ln52_73_fu_603_p2 + add_ln52_77_fu_610_p2);

assign add_ln52_4_fu_642_p2 = (add_ln52_80_fu_631_p2 + add_ln52_84_fu_638_p2);

assign add_ln52_59_fu_542_p2 = ($signed(grp_fu_762_p3) + $signed(sext_ln52_fu_539_p1));

assign add_ln52_5_fu_670_p2 = (add_ln52_87_fu_659_p2 + add_ln52_91_fu_666_p2);

assign add_ln52_63_fu_553_p2 = ($signed(sext_ln52_11_fu_547_p1) + $signed(grp_fu_807_p3));

assign add_ln52_66_fu_575_p2 = ($signed(grp_fu_831_p3) + $signed(grp_fu_840_p3));

assign add_ln52_6_fu_698_p2 = (add_ln52_94_fu_687_p2 + add_ln52_98_fu_694_p2);

assign add_ln52_70_fu_582_p2 = ($signed(grp_fu_861_p3) + $signed(grp_fu_870_p3));

assign add_ln52_73_fu_603_p2 = ($signed(grp_fu_894_p3) + $signed(grp_fu_903_p3));

assign add_ln52_77_fu_610_p2 = ($signed(grp_fu_918_p3) + $signed(grp_fu_933_p3));

assign add_ln52_7_fu_734_p2 = (add_ln52_101_fu_718_p2 + add_ln52_105_fu_729_p2);

assign add_ln52_80_fu_631_p2 = ($signed(grp_fu_951_p3) + $signed(grp_fu_966_p3));

assign add_ln52_84_fu_638_p2 = ($signed(grp_fu_981_p3) + $signed(grp_fu_996_p3));

assign add_ln52_87_fu_659_p2 = ($signed(grp_fu_1014_p3) + $signed(grp_fu_1029_p3));

assign add_ln52_91_fu_666_p2 = ($signed(grp_fu_1050_p3) + $signed(grp_fu_1059_p3));

assign add_ln52_94_fu_687_p2 = ($signed(grp_fu_1077_p3) + $signed(grp_fu_1098_p3));

assign add_ln52_98_fu_694_p2 = ($signed(grp_fu_1107_p3) + $signed(grp_fu_1122_p3));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == ap_ce) | ((ap_start == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign grp_fu_1005_p0 = sext_ln50_92_fu_535_p1;

assign grp_fu_1005_p1 = 28'd2896;

assign grp_fu_1005_p2 = 28'd4096;

assign grp_fu_1014_p0 = sext_ln50_54_fu_349_p1;

assign grp_fu_1014_p1 = 29'd2276;

assign grp_fu_1029_p1 = 27'd799;

assign grp_fu_1050_p1 = 27'd134216929;

assign grp_fu_1059_p0 = sext_ln50_78_fu_445_p1;

assign grp_fu_1059_p1 = 29'd4017;

assign grp_fu_1068_p0 = sext_ln50_92_fu_535_p1;

assign grp_fu_1068_p1 = 28'd268433180;

assign grp_fu_1068_p2 = 28'd4096;

assign grp_fu_1077_p1 = 28'd1567;

assign grp_fu_1098_p1 = 28'd268433889;

assign grp_fu_1107_p1 = 28'd268433889;

assign grp_fu_1122_p0 = sext_ln50_78_fu_445_p1;

assign grp_fu_1122_p1 = 29'd536867128;

assign grp_fu_1131_p1 = 27'd1567;

assign grp_fu_1131_p2 = 27'd4096;

assign grp_fu_1140_p1 = 27'd799;

assign grp_fu_1155_p0 = sext_ln50_62_fu_381_p1;

assign grp_fu_1155_p1 = 29'd3406;

assign grp_fu_1170_p0 = sext_ln50_69_fu_409_p1;

assign grp_fu_1170_p1 = 29'd4017;

assign grp_fu_1185_p0 = sext_ln50_77_fu_441_p1;

assign grp_fu_1185_p1 = 28'd2276;

assign grp_fu_1194_p1 = 26'd67108065;

assign grp_fu_1194_p2 = 26'd4096;

assign grp_fu_751_p2 = 29'd2896;

assign grp_fu_751_p3 = 29'd4096;

assign grp_fu_762_p0 = sext_ln50_54_fu_349_p1;

assign grp_fu_762_p1 = 29'd4017;

assign grp_fu_783_p1 = 27'd799;

assign grp_fu_792_p1 = 27'd134216929;

assign grp_fu_807_p0 = sext_ln50_78_fu_445_p1;

assign grp_fu_807_p1 = 29'd536867506;

assign grp_fu_816_p0 = sext_ln50_92_fu_535_p1;

assign grp_fu_816_p1 = 28'd268431439;

assign grp_fu_816_p2 = 28'd4096;

assign grp_fu_831_p0 = sext_ln50_57_fu_361_p1;

assign grp_fu_831_p1 = 28'd1567;

assign grp_fu_840_p0 = sext_ln50_61_fu_377_p1;

assign grp_fu_840_p1 = 28'd268433889;

assign grp_fu_861_p0 = sext_ln50_73_fu_425_p1;

assign grp_fu_861_p1 = 28'd268433889;

assign grp_fu_870_p0 = sext_ln50_77_fu_441_p1;

assign grp_fu_870_p1 = 28'd1567;

assign grp_fu_879_p0 = sext_ln50_92_fu_535_p1;

assign grp_fu_879_p1 = 28'd3784;

assign grp_fu_879_p2 = 28'd4096;

assign grp_fu_894_p1 = 27'd134216929;

assign grp_fu_903_p0 = sext_ln50_62_fu_381_p1;

assign grp_fu_903_p1 = 29'd536866895;

assign grp_fu_918_p0 = sext_ln50_69_fu_409_p1;

assign grp_fu_918_p1 = 29'd2276;

assign grp_fu_933_p1 = 27'd799;

assign grp_fu_942_p0 = sext_ln50_92_fu_535_p1;

assign grp_fu_942_p1 = 28'd268432050;

assign grp_fu_942_p2 = 28'd4096;

assign grp_fu_951_p0 = sext_ln50_54_fu_349_p1;

assign grp_fu_951_p1 = 29'd2896;

assign grp_fu_966_p0 = sext_ln50_62_fu_381_p1;

assign grp_fu_966_p1 = 29'd536868016;

assign grp_fu_981_p0 = sext_ln50_69_fu_409_p1;

assign grp_fu_981_p1 = 29'd2896;

assign grp_fu_996_p0 = sext_ln50_78_fu_445_p1;

assign grp_fu_996_p1 = 29'd536868016;

assign input_0_address0 = input_offset_cast_fu_318_p1;

assign input_1_address0 = input_offset_cast_fu_318_p1;

assign input_2_address0 = input_offset_cast_fu_318_p1;

assign input_3_address0 = input_offset_cast_fu_318_p1;

assign input_4_address0 = input_offset_cast_fu_318_p1;

assign input_5_address0 = input_offset_cast_fu_318_p1;

assign input_6_address0 = input_offset_cast_fu_318_p1;

assign input_7_address0 = input_offset_cast_fu_318_p1;

assign input_offset_cast_fu_318_p1 = input_offset;

assign mul_ln50_102_fu_1115_p0 = sext_ln50_74_fu_429_p1;

assign mul_ln50_102_fu_1115_p1 = 29'd3784;

assign mul_ln50_106_fu_1148_p0 = sext_ln50_57_fu_361_p1;

assign mul_ln50_106_fu_1148_p1 = 28'd268433180;

assign mul_ln50_108_fu_1163_p0 = sext_ln50_65_fu_393_p1;

assign mul_ln50_108_fu_1163_p1 = 29'd536866895;

assign mul_ln50_110_fu_1178_p0 = sext_ln50_74_fu_429_p1;

assign mul_ln50_110_fu_1178_p1 = 29'd536867506;

assign mul_ln50_58_fu_770_p0 = sext_ln50_58_fu_365_p1;

assign mul_ln50_58_fu_770_p1 = 29'd3406;

assign mul_ln50_59_fu_777_p0 = sext_ln50_61_fu_377_p1;

assign mul_ln50_59_fu_777_p1 = 28'd2276;

assign mul_ln50_62_fu_800_p0 = sext_ln50_73_fu_425_p1;

assign mul_ln50_62_fu_800_p1 = 28'd268433180;

assign mul_ln50_65_fu_825_p0 = sext_ln50_54_fu_349_p1;

assign mul_ln50_65_fu_825_p1 = 29'd3784;

assign mul_ln50_68_fu_848_p0 = sext_ln50_65_fu_393_p1;

assign mul_ln50_68_fu_848_p1 = 29'd536867128;

assign mul_ln50_69_fu_855_p0 = sext_ln50_69_fu_409_p1;

assign mul_ln50_69_fu_855_p1 = 29'd536867128;

assign mul_ln50_73_fu_888_p0 = sext_ln50_54_fu_349_p1;

assign mul_ln50_73_fu_888_p1 = 29'd3406;

assign mul_ln50_76_fu_911_p0 = sext_ln50_65_fu_393_p1;

assign mul_ln50_76_fu_911_p1 = 29'd536868636;

assign mul_ln50_78_fu_926_p0 = sext_ln50_74_fu_429_p1;

assign mul_ln50_78_fu_926_p1 = 29'd4017;

assign mul_ln50_82_fu_959_p0 = sext_ln50_58_fu_365_p1;

assign mul_ln50_82_fu_959_p1 = 29'd536868016;

assign mul_ln50_84_fu_974_p0 = sext_ln50_65_fu_393_p1;

assign mul_ln50_84_fu_974_p1 = 29'd2896;

assign mul_ln50_86_fu_989_p0 = sext_ln50_74_fu_429_p1;

assign mul_ln50_86_fu_989_p1 = 29'd536868016;

assign mul_ln50_90_fu_1022_p0 = sext_ln50_58_fu_365_p1;

assign mul_ln50_90_fu_1022_p1 = 29'd536866895;

assign mul_ln50_92_fu_1037_p0 = sext_ln50_65_fu_393_p1;

assign mul_ln50_92_fu_1037_p1 = 29'd3406;

assign mul_ln50_93_fu_1044_p0 = sext_ln50_69_fu_409_p1;

assign mul_ln50_93_fu_1044_p1 = 29'd536867506;

assign mul_ln50_98_fu_1085_p0 = sext_ln50_58_fu_365_p1;

assign mul_ln50_98_fu_1085_p1 = 29'd536867128;

assign mul_ln50_99_fu_1092_p0 = sext_ln50_62_fu_381_p1;

assign mul_ln50_99_fu_1092_p1 = 29'd3784;

assign output_offset_cast_fu_330_p1 = output_offset_read_reg_1203;

assign sext_ln50_54_fu_349_p0 = input_0_q0;

assign sext_ln50_54_fu_349_p1 = sext_ln50_54_fu_349_p0;

assign sext_ln50_55_fu_353_p0 = input_0_q0;

assign sext_ln50_55_fu_353_p1 = sext_ln50_55_fu_353_p0;

assign sext_ln50_57_fu_361_p0 = input_1_q0;

assign sext_ln50_57_fu_361_p1 = sext_ln50_57_fu_361_p0;

assign sext_ln50_58_fu_365_p0 = input_1_q0;

assign sext_ln50_58_fu_365_p1 = sext_ln50_58_fu_365_p0;

assign sext_ln50_59_fu_369_p0 = input_1_q0;

assign sext_ln50_59_fu_369_p1 = sext_ln50_59_fu_369_p0;

assign sext_ln50_61_fu_377_p0 = input_2_q0;

assign sext_ln50_61_fu_377_p1 = sext_ln50_61_fu_377_p0;

assign sext_ln50_62_fu_381_p0 = input_2_q0;

assign sext_ln50_62_fu_381_p1 = sext_ln50_62_fu_381_p0;

assign sext_ln50_63_fu_385_p0 = input_2_q0;

assign sext_ln50_63_fu_385_p1 = sext_ln50_63_fu_385_p0;

assign sext_ln50_65_fu_393_p0 = input_3_q0;

assign sext_ln50_65_fu_393_p1 = sext_ln50_65_fu_393_p0;

assign sext_ln50_67_fu_401_p0 = input_3_q0;

assign sext_ln50_67_fu_401_p1 = sext_ln50_67_fu_401_p0;

assign sext_ln50_69_fu_409_p0 = input_4_q0;

assign sext_ln50_69_fu_409_p1 = sext_ln50_69_fu_409_p0;

assign sext_ln50_71_fu_417_p0 = input_4_q0;

assign sext_ln50_71_fu_417_p1 = sext_ln50_71_fu_417_p0;

assign sext_ln50_73_fu_425_p0 = input_5_q0;

assign sext_ln50_73_fu_425_p1 = sext_ln50_73_fu_425_p0;

assign sext_ln50_74_fu_429_p0 = input_5_q0;

assign sext_ln50_74_fu_429_p1 = sext_ln50_74_fu_429_p0;

assign sext_ln50_75_fu_433_p0 = input_5_q0;

assign sext_ln50_75_fu_433_p1 = sext_ln50_75_fu_433_p0;

assign sext_ln50_77_fu_441_p0 = input_6_q0;

assign sext_ln50_77_fu_441_p1 = sext_ln50_77_fu_441_p0;

assign sext_ln50_78_fu_445_p0 = input_6_q0;

assign sext_ln50_78_fu_445_p1 = sext_ln50_78_fu_445_p0;

assign sext_ln50_79_fu_449_p0 = input_6_q0;

assign sext_ln50_79_fu_449_p1 = sext_ln50_79_fu_449_p0;

assign sext_ln50_82_fu_461_p0 = input_7_q0;

assign sext_ln50_82_fu_461_p1 = sext_ln50_82_fu_461_p0;

assign sext_ln50_83_fu_471_p1 = $signed(add_ln50_fu_465_p2);

assign sext_ln50_84_fu_481_p1 = $signed(add_ln50_7_fu_475_p2);

assign sext_ln50_86_fu_501_p1 = $signed(add_ln50_9_fu_495_p2);

assign sext_ln50_87_fu_511_p1 = $signed(add_ln50_10_fu_505_p2);

assign sext_ln50_92_fu_535_p0 = input_7_q0;

assign sext_ln50_92_fu_535_p1 = sext_ln50_92_fu_535_p0;

assign sext_ln52_11_fu_547_p1 = grp_fu_792_p3;

assign sext_ln52_18_fu_715_p1 = grp_fu_1140_p3;

assign sext_ln52_20_fu_726_p1 = grp_fu_1185_p3;

assign sext_ln52_fu_539_p1 = grp_fu_783_p3;

endmodule //DCT_1D
